class InsertUserException(Exception):
    pass

class GetUserException(Exception):
    pass